# Generated by Django 4.1.4 on 2023-04-07 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(default='', max_length=100)),
                ('mobile', models.CharField(default='', max_length=10)),
                ('age', models.CharField(default='', max_length=4)),
                ('gender', models.CharField(default='', max_length=10)),
                ('Passward', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
